### ISSUE TITLE
fails on windows

### ISSUE THREAD

**Issue by mchave** [carlosvin/cpp_gradle#2]
As this example is written, on windows to use the dynamic library you'll need to export the class:

...
class __declspec( dllexport ) Hello 
...

Or use a DEF file, or some other method. Otherwise, out of the box it will fail complaining about missing the import library which would have gone with the DLL.

**Comment by carlosvin** [comment]
For now I cannot investigate the issue, I don't have windows on my PC.

**Comment by carlosvin** [comment]
I'll close this issue because it will be addressed with #4
